/**
 * Orval codegen config.
 * Sync openapi/api-docs.json from chn_backend/.cursor/api-docs.json before each milestone.
 */
export default {
  chn: {
    input: './openapi/api-docs.json',
    output: {
      mode: 'split',
      target: './src/api/generated/endpoints.ts',
      schemas: './src/api/generated/models',
      client: 'fetch',
      override: {
        header: () => [
          '/** Generated by Orval — do not edit. Run: npm run codegen */',
        ],
      },
    },
  },
};
